### ISSUE TITLE
Browser crashes when clicking reload on Startpage

### ISSUE THREAD

**Issue by DavidBoom200** [Simooonnnnn/CsNet-Browser#1]
When clicking reload on the "CsNet" Startpage, the browser crashes.

The unhandled exception happens here:
![image](https://github.com/user-attachments/assets/600aa27c-0df5-4f96-be54-1afb17a2905c)
...in the File "MainWindow.xaml.cs"

**Comment by Simooonnnnn** [comment]
Problem got fixed in the latest release.
